---
title: "[USA] President Election 1976 ~ 2020 (v1, clean)" 
author: "sw1kwon"
date: "09/09/2025"
draft: false
categories: [usa-president, usa-clean-v1]
---

# Raw Data

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/original/Presidential_Elections/1976-2020-president.csv')

In [2]:
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
2,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"MADDOX, LESTER",AMERICAN INDEPENDENT PARTY,False,9198,1182850,20210113,NaN,OTHER
3,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"BUBAR, BENJAMIN """"BEN""""",PROHIBITION,False,6669,1182850,20210113,NaN,OTHER
4,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"HALL, GUS",COMMUNIST PARTY USE,False,1954,1182850,20210113,NaN,OTHER

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4287 entries, 0 to 4286
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              4287 non-null   int64
 1   state             4287 non-null   object
 2   state_po          4287 non-null   object
 3   state_fips        4287 non-null   int64
 4   state_cen         4287 non-null   int64
 5   state_ic          4287 non-null   int64
 6   office            4287 non-null   object
 7   candidate         4000 non-null   object
 8   party_detailed    3831 non-null   object
 9   writein           4284 non-null   object
 10  candidatevotes    4287 non-null   int64
 11  totalvotes        4287 non-null   int64
 12  version           4287 non-null   int64
 13  notes             0 non-null      float64
 14  party_simplified  4287 non-null   object
dtypes: float64(1), int64(7), object(7)
memory usage: 502.5+ KB

In [4]:
df['party_simplified'].value_counts(dropna=False)

party_simplified
OTHER          2524
DEMOCRAT        615
REPUBLICAN      613
LIBERTARIAN     535
Name: count, dtype: int64

# v1

## writein NaN

In [5]:
df['writein'] = df['writein'].astype(str)

In [6]:
df['writein'].value_counts(dropna=False)

writein
False    3807
True      477
nan         3
Name: count, dtype: int64

In [7]:
df.query("year == 2020 and state_po == 'MD'  and writein == 'nan'")

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
4011,2020,MARYLAND,MD,24,52,52,US PRESIDENT,"RALEY, ALBERT",NaN,nan,32,3037030,20210113,NaN,OTHER
4012,2020,MARYLAND,MD,24,52,52,US PRESIDENT,"SCHAWLB, BENJAMIN",NaN,nan,3,3037030,20210113,NaN,OTHER
4013,2020,MARYLAND,MD,24,52,52,US PRESIDENT,NaN,NaN,nan,18045,3037030,20210113,NaN,OTHER

- https://en.wikipedia.org/wiki/2020_United_States_presidential_election_in_Maryland#Results
- Write-in: 20,422

In [8]:
df.query("year == 2020 and state_po == 'MD'  and writein == 'True'")['candidatevotes'].sum()

np.int64(2342)

In [9]:
df['writein'] = df['writein'].mask(
    (df['year'] == 2020) &
    (df['state_po'] == "MD") &
    (df['writein'] == "nan"),
    "True"
)

In [10]:
df.query("year == 2020 and state_po == 'MD'  and writein == 'True'")['candidatevotes'].sum()

np.int64(20422)

## writein True False

- https://electionresults.dcboe.org/election_statistics/2020-General-Election
- Write-in: 3,137

In [11]:
df.loc[(df['year'] == 2020) & (df['state_po'] == "DC")]

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
3842,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,True,317323,344356,20210113,NaN,DEMOCRAT
3843,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,True,18586,344356,20210113,NaN,REPUBLICAN
3844,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"JORGENSEN, JO",LIBERTARIAN,True,2036,344356,20210113,NaN,LIBERTARIAN
3845,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"HAWKINS, HOWIE",DC STATEHOOD GREEN,True,1726,344356,20210113,NaN,OTHER
3846,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"LA RIVA, GLORIA ESTELLA",INDEPENDENT,True,855,344356,20210113,NaN,OTHER
3847,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,NaN,NaN,True,3137,344356,20210113,NaN,OTHER
3848,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"PIERCE, BROCK",INDEPENDENT,False,693,344356,20210113,NaN,OTHER

In [12]:
df['writein'] = df['writein'].mask(
    (df['year'] == 2020) &
    (df['state_po'] == "DC") &
    (df['candidatevotes'] != 3137) &
    (df['writein'] == "True"),
    "False"
)

In [13]:
df.loc[(df['year'] == 2020) & (df['state_po'] == "DC")]

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
3842,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,False,317323,344356,20210113,NaN,DEMOCRAT
3843,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,18586,344356,20210113,NaN,REPUBLICAN
3844,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"JORGENSEN, JO",LIBERTARIAN,False,2036,344356,20210113,NaN,LIBERTARIAN
3845,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"HAWKINS, HOWIE",DC STATEHOOD GREEN,False,1726,344356,20210113,NaN,OTHER
3846,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"LA RIVA, GLORIA ESTELLA",INDEPENDENT,False,855,344356,20210113,NaN,OTHER
3847,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,NaN,NaN,True,3137,344356,20210113,NaN,OTHER
3848,2020,DISTRICT OF COLUMBIA,DC,11,53,55,US PRESIDENT,"PIERCE, BROCK",INDEPENDENT,False,693,344356,20210113,NaN,OTHER

## csv

In [14]:
df.to_csv("1976-2020-president_v1.csv", index=False, encoding="utf-8-sig")