---
title: "[USA] President Election 2024 (v1, clean)" 
author: "sw1kwon"
date: "10/04/2025"
draft: false
categories: [usa-president, usa-clean-v1]
---

# Raw Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/original/Presidential_Elections2/countypres_2000-2024.csv')\
     .query('year == 2024').drop(columns=['county_fips', 'office', 'version']).reset_index(drop=True)

df.head()

,year,state,state_po,county_name,candidate,party,candidatevotes,totalvotes,mode
0,2024,ALABAMA,AL,AUTAUGA,CHASE OLIVER,LIBERTARIAN,65,28281,TOTAL VOTES
1,2024,ALABAMA,AL,AUTAUGA,DONALD J TRUMP,REPUBLICAN,20484,28281,TOTAL VOTES
2,2024,ALABAMA,AL,AUTAUGA,KAMALA D HARRIS,DEMOCRAT,7439,28281,TOTAL VOTES
3,2024,ALABAMA,AL,AUTAUGA,OTHER,OTHER,293,28281,TOTAL VOTES
4,2024,ALABAMA,AL,BALDWIN,CHASE OLIVER,LIBERTARIAN,241,122249,TOTAL VOTES

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/original/Presidential_Elections2/countypres_2000-2024.csv')\
     .query('year == 2024').reset_index(drop=True)

df.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2024,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,65,28281,20250821,TOTAL VOTES
1,2024,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484,28281,20250821,TOTAL VOTES
2,2024,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439,28281,20250821,TOTAL VOTES
3,2024,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,293,28281,20250821,TOTAL VOTES
4,2024,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,241,122249,20250821,TOTAL VOTES

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21792 entries, 0 to 21791
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            21792 non-null  int64
 1   state           21792 non-null  object
 2   state_po        21792 non-null  object
 3   county_name     21792 non-null  object
 4   county_fips     21792 non-null  float64
 5   office          21792 non-null  object
 6   candidate       21792 non-null  object
 7   party           21291 non-null  object
 8   candidatevotes  21792 non-null  int64
 9   totalvotes      21792 non-null  int64
 10  version         21792 non-null  int64
 11  mode            18103 non-null  object
dtypes: float64(1), int64(4), object(7)
memory usage: 2.0+ MB

# CSV

In [5]:
df.to_csv("2024-president_v1.csv", index=False, encoding="utf-8-sig")

# Plan to preprocess based on mode later

In [6]:
df_mode = df.groupby('state')['mode'].unique().reset_index()
df_mode

                   state                                               mode
0                ALABAMA                                      [TOTAL VOTES]
1                 ALASKA                                      [TOTAL VOTES]
2                ARIZONA  [EARLY VOTING, ELECTION DAY, PROVISIONAL, TOTA...
3               ARKANSAS  [ABSENTEE, EARLY VOTING, ELECTION DAY, PROVISI...
4             CALIFORNIA                                      [TOTAL VOTES]
5               COLORADO                                      [TOTAL VOTES]
6            CONNECTICUT                                      [TOTAL VOTES]
7               DELAWARE                                      [TOTAL VOTES]
8   DISTRICT OF COLUMBIA                                      [TOTAL VOTES]
9                FLORIDA                                      [TOTAL VOTES]
10               GEORGIA                                      [TOTAL VOTES]
11                HAWAII                                      [TOTAL VOTES]
12                 IDAHO                                              [nan]
13              ILLINOIS                                      [TOTAL VOTES]
14               INDIANA                                      [TOTAL VOTES]
15                  IOWA              [ABSENTEE, ELECTION DAY, TOTAL VOTES]
16                KANSAS                                              [nan]
17              KENTUCKY                                      [TOTAL VOTES]
18             LOUISIANA           [EARLY VOTING, PROVISIONAL, TOTAL VOTES]
19                 MAINE                                      [TOTAL VOTES]
20              MARYLAND                                      [TOTAL VOTES]
21         MASSACHUSETTS                                      [TOTAL VOTES]
22              MICHIGAN                                      [TOTAL VOTES]
23             MINNESOTA                                      [TOTAL VOTES]
24           MISSISSIPPI                                      [TOTAL VOTES]
25              MISSOURI                                      [TOTAL VOTES]
26               MONTANA                                      [TOTAL VOTES]
27              NEBRASKA                                      [TOTAL VOTES]
28                NEVADA                                      [TOTAL VOTES]
29         NEW HAMPSHIRE                                      [TOTAL VOTES]
30            NEW JERSEY                                      [TOTAL VOTES]
31            NEW MEXICO             [ABSENTEE, EARLY VOTING, ELECTION DAY]
32              NEW YORK                                      [TOTAL VOTES]
33        NORTH CAROLINA                                              [nan]
34          NORTH DAKOTA                                      [TOTAL VOTES]
35                  OHIO                                      [TOTAL VOTES]
36              OKLAHOMA  [ABSENTEE, EARLY VOTING, ELECTION DAY, TOTAL V...
37                OREGON                                      [TOTAL VOTES]
38          PENNSYLVANIA  [ELECTION DAY, MAIL-IN, PROVISIONAL, TOTAL VOTES]
39          RHODE ISLAND                                              [nan]
40        SOUTH CAROLINA  [ABSENTEE, EARLY VOTING, ELECTION DAY, FAILSAF...
41          SOUTH DAKOTA                         [TOTAL VOTES, VOTE CENTER]
42             TENNESSEE                                      [TOTAL VOTES]
43                 TEXAS                   [nan, EARLY VOTING, TOTAL VOTES]
44                  UTAH                                              [nan]
45               VERMONT                                              [nan]
46              VIRGINIA                                      [TOTAL VOTES]
47            WASHINGTON                                              [nan]
48         WEST VIRGINIA                                              [nan]
49             WISCONSIN                                              [nan]
50               WYOMING                                              [nan]

In [7]:
df_mode['mode'].astype(str).unique()

array(["['TOTAL VOTES']",
       "['EARLY VOTING' 'ELECTION DAY' 'PROVISIONAL' 'TOTAL VOTES'\n 'LATE EARLY VOTING']",
       "['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'PROVISIONAL' 'TOTAL VOTES']",
       '[nan]', "['ABSENTEE' 'ELECTION DAY' 'TOTAL VOTES']",
       "['EARLY VOTING' 'PROVISIONAL' 'TOTAL VOTES']",
       "['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY']",
       "['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'TOTAL VOTES']",
       "['ELECTION DAY' 'MAIL-IN' 'PROVISIONAL' 'TOTAL VOTES']",
       "['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'FAILSAFE PROVISIONAL'\n 'PROVISIONAL' 'TOTAL VOTES']",
       "['TOTAL VOTES' 'VOTE CENTER']",
       "[nan 'EARLY VOTING' 'TOTAL VOTES']"], dtype=object)

In [8]:
(df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
)

mode_str
['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'FAILSAFE PROVISIONAL'\n 'PROVISIONAL' 'TOTAL VOTES']                                     [SOUTH CAROLINA]
['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'PROVISIONAL' 'TOTAL VOTES']                                                                    [ARKANSAS]
['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY' 'TOTAL VOTES']                                                                                  [OKLAHOMA]
['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY']                                                                                              [NEW MEXICO]
['ABSENTEE' 'ELECTION DAY' 'TOTAL VOTES']                                                                                                     [IOWA]
['EARLY VOTING' 'ELECTION DAY' 'PROVISIONAL' 'TOTAL VOTES'\n 'LATE EARLY VOTING']                                                          [ARIZONA]
['EARLY VOTING' 'PROVISIONAL' 'TOTAL VOTES']                                                                                             [LOUISIANA]
['ELECTION DAY' 'MAIL-IN' 'PROVISIONAL' 'TOTAL VOTES']                                                                                [PENNSYLVANIA]
['TOTAL VOTES' 'VOTE CENTER']                                                                                                         [SOUTH DAKOTA]
['TOTAL VOTES']                                                                                    [ALABAMA, ALASKA, CALIFORNIA, COLORADO, CONNEC...
[nan 'EARLY VOTING' 'TOTAL VOTES']                                                                                                           [TEXAS]
[nan]                                                                                              [IDAHO, KANSAS, NORTH CAROLINA, RHODE ISLAND, ...
Name: state, dtype: object

- NEW MEXICO = ['ABSENTEE' 'EARLY VOTING' 'ELECTION DAY']
- TEXAS = [nan 'EARLY VOTING' 'TOTAL VOTES']

In [9]:
# TOTAL VOTES only
(df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
)

['ALABAMA',
 'ALASKA',
 'CALIFORNIA',
 'COLORADO',
 'CONNECTICUT',
 'DELAWARE',
 'DISTRICT OF COLUMBIA',
 'FLORIDA',
 'GEORGIA',
 'HAWAII',
 'ILLINOIS',
 'INDIANA',
 'KENTUCKY',
 'MAINE',
 'MARYLAND',
 'MASSACHUSETTS',
 'MICHIGAN',
 'MINNESOTA',
 'MISSISSIPPI',
 'MISSOURI',
 'MONTANA',
 'NEBRASKA',
 'NEVADA',
 'NEW HAMPSHIRE',
 'NEW JERSEY',
 'NEW YORK',
 'NORTH DAKOTA',
 'OHIO',
 'OREGON',
 'TENNESSEE',
 'VIRGINIA']

In [10]:
# Including TOTAL VOTES
df.query("mode == 'TOTAL VOTES'")['state'].unique()

array(['ALABAMA', 'ALASKA', 'ARIZONA', 'ARKANSAS', 'CALIFORNIA',
       'COLORADO', 'CONNECTICUT', 'DELAWARE', 'DISTRICT OF COLUMBIA',
       'FLORIDA', 'GEORGIA', 'HAWAII', 'ILLINOIS', 'INDIANA', 'IOWA',
       'KENTUCKY', 'LOUISIANA', 'MAINE', 'MARYLAND', 'MASSACHUSETTS',
       'MICHIGAN', 'MINNESOTA', 'MISSISSIPPI', 'MISSOURI', 'MONTANA',
       'NEBRASKA', 'NEVADA', 'NEW HAMPSHIRE', 'NEW JERSEY', 'NEW YORK',
       'NORTH DAKOTA', 'OHIO', 'OKLAHOMA', 'OREGON', 'PENNSYLVANIA',
       'SOUTH CAROLINA', 'SOUTH DAKOTA', 'TENNESSEE', 'TEXAS', 'VIRGINIA'],
      dtype=object)

In [11]:
# TOTAL VOTES + other modes
set(df.query("mode == 'TOTAL VOTES'")['state'].unique()) - set((df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
))

{'ARIZONA',
 'ARKANSAS',
 'IOWA',
 'LOUISIANA',
 'OKLAHOMA',
 'PENNSYLVANIA',
 'SOUTH CAROLINA',
 'SOUTH DAKOTA',
 'TEXAS'}

In [12]:
# nan only
(df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["[nan]"]
)

['IDAHO',
 'KANSAS',
 'NORTH CAROLINA',
 'RHODE ISLAND',
 'UTAH',
 'VERMONT',
 'WASHINGTON',
 'WEST VIRGINIA',
 'WISCONSIN',
 'WYOMING']

In [13]:
# TOTAL VOTES only + (TOTAL VOTES + other modes) + nan only = 50
len((df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
)) + len(set(df.query("mode == 'TOTAL VOTES'")['state'].unique()) - set((df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
))) + len((df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["[nan]"]
))

50

In [14]:
# NEW MEXICO (other modes, no TOTAL VOTES)
set(df_mode['state'].unique()) - set(
    (df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
)
) - (set(df.query("mode == 'TOTAL VOTES'")['state'].unique()) - set((df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["['TOTAL VOTES']"]
))) - set(
    (df_mode
    .assign(mode_str=lambda x: x['mode'].astype(str))
    .groupby('mode_str')['state']
    .apply(list)
    .loc["[nan]"]
)
)

{'NEW MEXICO'}